import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  generateE2EEKeyPairLocal,
  reencryptPrivateKey,
  unlockPrivateKey,
  verifyPrivateKeyMatchesPub,
} from '../src/crypto/e2ee-local.js';
import { pathsForMainDir } from '../src/profile/paths.js';
import {
  generateRandomPassphrase,
  readPassphraseFile,
  resolvePassphrase,
  writePassphrase,
} from '../src/profile/passphrase.js';
import {
  redactAbsolutePaths,
  sanitizeGateMessages,
  sanitizeGateWarnings,
  sanitizeWalletSummaries,
  HUMAN_ONLY_ERROR,
} from '../src/tools/guard.js';
import { withProfileContext } from '../src/tools/sanitize.js';

describe('passphrase store', () => {
  it('generates random passphrase of sufficient length', () => {
    const p = generateRandomPassphrase();
    expect(p.length).toBeGreaterThanOrEqual(24);
  });

  it('auto-generates and writes e2ee.passphrase', async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tmail-pass-'));
    const slug = '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef';
    const paths = pathsForMainDir(dir, path.join(dir, '.tmail'), slug);
    fs.mkdirSync(paths.dir, { recursive: true, mode: 0o700 });

    const resolved = await resolvePassphrase(paths, { autoGenerate: true });
    expect(resolved.autoGenerated).toBe(true);
    const stored = await readPassphraseFile(paths.e2eePassphraseFile);
    expect(stored).toBe(resolved.passphrase);
  });

  it('writes passphrase with meta', async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tmail-pass-'));
    const slug = '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef';
    const paths = pathsForMainDir(dir, path.join(dir, '.tmail'), slug);
    fs.mkdirSync(paths.dir, { recursive: true, mode: 0o700 });
    await writePassphrase(paths, 'sixteen-characters-min', true);
    const stored = await readPassphraseFile(paths.e2eePassphraseFile);
    expect(stored).toBe('sixteen-characters-min');
    const meta = JSON.parse(fs.readFileSync(paths.e2eePassphraseMetaFile, 'utf8')) as { user_set: boolean };
    expect(meta.user_set).toBe(true);
  });
});

describe('e2ee unlock roundtrip', () => {
  it('reencrypt preserves public key', async () => {
    const passphrase = 'sixteen-characters-min';
    const out = await generateE2EEKeyPairLocal(passphrase);
    const enc = String(out.enc_priv_key_base64);
    const salt = String(out.pbkdf2_salt);
    const iterations = Number(out.pbkdf2_iterations);
    const pub = String(out.pub_key_base64);

    const priv = unlockPrivateKey(enc, salt, iterations, passphrase);
    expect(verifyPrivateKeyMatchesPub(priv, pub)).toBe(true);

    const newPass = 'another-passphrase-16chars';
    const reenc = await reencryptPrivateKey(priv, newPass);
    const priv2 = unlockPrivateKey(reenc.enc_priv_key_base64, reenc.pbkdf2_salt, reenc.pbkdf2_iterations, newPass);
    expect(verifyPrivateKeyMatchesPub(priv2, pub)).toBe(true);
    priv.fill(0);
    priv2.fill(0);
  });
});

describe('gate redaction', () => {
  it('redacts Profile and Main lines', () => {
    const out = sanitizeGateMessages(['READY', 'Main: /var/lib/x', 'Profile: /var/lib/x/y', 'Wallet: abc']);
    expect(out).toEqual(['READY', 'Main: [redacted]', 'Profile: [redacted]', 'Wallet: abc']);
  });

  it('redacts absolute paths in arbitrary messages', () => {
    const raw = 'Partial profile: delete /var/lib/tmail-profiles/.tmail/abc/profile/session.json';
    expect(redactAbsolutePaths(raw)).not.toContain('/var/lib');
    expect(sanitizeGateMessages([raw])[0]).not.toContain('/var/lib');
  });

  it('redacts absolute paths in warnings', () => {
    const out = sanitizeGateWarnings(['rm -rf /var/lib/tmail-profiles/.tmail/_pending']);
    expect(out?.[0]).not.toContain('/var/lib');
  });

  it('strips profile_dir from wallet summaries', () => {
    const out = sanitizeWalletSummaries([
      { wallet_slug: 'abc', sub_address: '0:x', profile_dir: '/secret/path' },
    ]);
    expect(out[0]).toEqual({ wallet_slug: 'abc', sub_address: '0:x' });
    expect(out[0]).not.toHaveProperty('profile_dir');
  });

  it('withProfileContext omits profile_dir by default', () => {
    const out = withProfileContext('slug', '/secret/profile', { ok: true });
    expect(out.profile_context).toEqual({ wallet_slug: 'slug' });
  });
});

describe('human-only gate', () => {
  it('exports stable error message', () => {
    expect(HUMAN_ONLY_ERROR).toContain('403 human_required');
  });
});
