import type { AgentType } from './types.js';

export const AGENT_DISPLAY_NAMES: Record<AgentType, string> = {
  'aider-desk': 'AiderDesk',
  'amp': 'Amp',
  'antigravity': 'Antigravity',
  'antigravity-cli': 'Antigravity CLI',
  'astrbot': 'AstrBot',
  'autohand-code': 'Autohand Code CLI',
  'augment': 'Augment',
  'bob': 'IBM Bob',
  'claude-code': 'Claude Code',
  'openclaw': 'OpenClaw',
  'cline': 'Cline',
  'codearts-agent': 'CodeArts Agent',
  'codebuddy': 'CodeBuddy',
  'codemaker': 'Codemaker',
  'codestudio': 'Code Studio',
  'codex': 'Codex',
  'command-code': 'Command Code',
  'continue': 'Continue',
  'cortex': 'Cortex Code',
  'crush': 'Crush',
  'cursor': 'Cursor',
  'deepagents': 'Deep Agents',
  'devin': 'Devin for Terminal',
  'dexto': 'Dexto',
  'droid': 'Droid',
  'eve': 'Eve',
  'firebender': 'Firebender',
  'forgecode': 'ForgeCode',
  'gemini-cli': 'Gemini CLI',
  'github-copilot': 'GitHub Copilot',
  'goose': 'Goose',
  'hermes-agent': 'Hermes Agent',
  'inference-sh': 'inference.sh',
  'jazz': 'Jazz',
  'junie': 'Junie',
  'iflow-cli': 'iFlow CLI',
  'kilo': 'Kilo Code',
  'kimi-code-cli': 'Kimi Code CLI',
  'kiro-cli': 'Kiro CLI',
  'kode': 'Kode',
  'lingma': 'Lingma',
  'loaf': 'Loaf',
  'mcpjam': 'MCPJam',
  'mistral-vibe': 'Mistral Vibe',
  'moxby': 'Moxby',
  'mux': 'Mux',
  'opencode': 'OpenCode',
  'openhands': 'OpenHands',
  'ona': 'Ona',
  'pi': 'Pi',
  'qoder': 'Qoder',
  'qoder-cn': 'Qoder CN',
  'qwen-code': 'Qwen Code',
  'replit': 'Replit',
  'reasonix': 'Reasonix',
  'rovodev': 'Rovo Dev',
  'roo': 'Roo Code',
  'tabnine-cli': 'Tabnine CLI',
  'terramind': 'Terramind',
  'tinycloud': 'Tinycloud',
  'trae': 'Trae',
  'trae-cn': 'Trae CN',
  'warp': 'Warp',
  'windsurf': 'Windsurf',
  'zed': 'Zed',
  'zencoder': 'Zencoder',
  'zenflow': 'Zenflow',
  'neovate': 'Neovate',
  'pochi': 'Pochi',
  'promptscript': 'PromptScript',
  'adal': 'AdaL',
  'universal': 'Universal',
};
