import fs from 'node:fs';
import path from 'node:path';
import { randomBytes } from 'node:crypto';
import type { ProfilePaths } from './paths.js';
import { writeJsonAtomic } from './jsonfields.js';

export const ENV_E2EE_PASSPHRASE = 'TMAIL_E2EE_PASSPHRASE';

export interface PassphraseMeta {
  user_set: boolean;
  generated_at: string;
  length: number;
}

export interface PassphraseStatus {
  set: boolean;
  user_set: boolean;
  length?: number;
  source?: 'file' | 'env' | 'none';
}

export function generateRandomPassphrase(): string {
  return randomBytes(18).toString('base64url');
}

export async function readPassphraseFile(filePath: string): Promise<string | null> {
  try {
    const content = (await fs.promises.readFile(filePath, 'utf8')).trim();
    return content.length > 0 ? content : null;
  } catch {
    return null;
  }
}

export async function readPassphraseMeta(paths: ProfilePaths): Promise<PassphraseMeta | null> {
  try {
    return JSON.parse(await fs.promises.readFile(paths.e2eePassphraseMetaFile, 'utf8')) as PassphraseMeta;
  } catch {
    return null;
  }
}

export async function writePassphrase(paths: ProfilePaths, passphrase: string, userSet: boolean): Promise<void> {
  const filePath = paths.e2eePassphraseFile;
  await fs.promises.mkdir(path.dirname(filePath), { recursive: true, mode: 0o700 });
  await fs.promises.writeFile(filePath, `${passphrase}\n`, { encoding: 'utf8', mode: 0o600 });
  const meta: PassphraseMeta = {
    user_set: userSet,
    generated_at: new Date().toISOString(),
    length: passphrase.length,
  };
  await writeJsonAtomic(paths.e2eePassphraseMetaFile, meta);
  try {
    await fs.promises.chmod(paths.e2eePassphraseMetaFile, 0o644);
  } catch {
    // best-effort
  }
}

export async function passphraseStatus(paths: ProfilePaths, envFallback?: string): Promise<PassphraseStatus> {
  const fromFile = await readPassphraseFile(paths.e2eePassphraseFile);
  if (fromFile) {
    const meta = await readPassphraseMeta(paths);
    return {
      set: true,
      user_set: meta?.user_set ?? false,
      length: fromFile.length,
      source: 'file',
    };
  }
  const env = envFallback?.trim();
  if (env) {
    return { set: true, user_set: true, length: env.length, source: 'env' };
  }
  return { set: false, user_set: false, source: 'none' };
}

export async function resolvePassphrase(
  paths: ProfilePaths,
  opts: { argsPassphrase?: string; envFallback?: string; autoGenerate?: boolean },
): Promise<{ passphrase: string; autoGenerated: boolean; source: string }> {
  const fromFile = await readPassphraseFile(paths.e2eePassphraseFile);
  if (fromFile) {
    if (fromFile.length < 16) throw new Error('stored passphrase too short (min 16 characters)');
    return { passphrase: fromFile, autoGenerated: false, source: 'file' };
  }
  const env = opts.envFallback?.trim();
  if (env) {
    if (env.length < 16) throw new Error('TMAIL_E2EE_PASSPHRASE too short (min 16 characters)');
    return { passphrase: env, autoGenerated: false, source: 'env' };
  }
  const args = opts.argsPassphrase?.trim();
  if (args) {
    if (args.length < 16) throw new Error('passphrase must be at least 16 characters');
    return { passphrase: args, autoGenerated: false, source: 'args' };
  }
  if (opts.autoGenerate === false) {
    throw new Error('no passphrase available — omit args for auto-generate or use e2ee-passphrase CLI');
  }
  const generated = generateRandomPassphrase();
  await writePassphrase(paths, generated, false);
  return { passphrase: generated, autoGenerated: true, source: 'generated' };
}

/** Move legacy `passphrase` field from e2ee.json into e2ee.passphrase file. */
export async function migrateLegacyPassphraseInJson(paths: ProfilePaths): Promise<boolean> {
  let profile: Record<string, unknown>;
  try {
    profile = JSON.parse(await fs.promises.readFile(paths.e2eeFile, 'utf8')) as Record<string, unknown>;
  } catch {
    return false;
  }
  const legacy = typeof profile.passphrase === 'string' ? profile.passphrase.trim() : '';
  if (!legacy) return false;

  const existing = await readPassphraseFile(paths.e2eePassphraseFile);
  if (!existing) {
    await writePassphrase(paths, legacy, true);
  }
  delete profile.passphrase;
  await writeJsonAtomic(paths.e2eeFile, profile);
  return true;
}

export function hasLegacyPassphraseInJson(e2eeFile: string): boolean {
  try {
    const profile = JSON.parse(fs.readFileSync(e2eeFile, 'utf8')) as Record<string, unknown>;
    return typeof profile.passphrase === 'string' && profile.passphrase.trim().length > 0;
  } catch {
    return false;
  }
}
