import fs from 'node:fs';
import {
  generateE2EEKeyPairLocal,
  reencryptPrivateKey,
  unlockPrivateKey,
  verifyPrivateKeyMatchesPub,
} from '../crypto/e2ee-local.js';
import { ERR_E2EE_ALREADY_REGISTERED, newResolveError } from '../profile/errors.js';
import { writeJsonAtomic } from '../profile/jsonfields.js';
import {
  migrateLegacyPassphraseInJson,
  passphraseStatus,
  readPassphraseFile,
  resolvePassphrase,
  writePassphrase,
} from '../profile/passphrase.js';
import { requireGate, requireHumanOnly } from './guard.js';
import { sanitizeForTool, withProfileContext } from './sanitize.js';
import {
  optionalString,
  requireString,
  requireStringArray,
  resolveErrorResult,
  textError,
  textResult,
  type Runtime,
} from './runtime.js';

async function writeE2EEProfile(filePath: string, apiOut: Record<string, unknown>): Promise<void> {
  const profile: Record<string, unknown> = {};
  for (const key of ['pub_key_base64', 'enc_priv_key_base64', 'pbkdf2_salt', 'pbkdf2_iterations', 'registered']) {
    if (key in apiOut) profile[key] = apiOut[key];
  }
  await writeJsonAtomic(filePath, profile);
}

async function mergeE2EERegistered(filePath: string): Promise<void> {
  let profile: Record<string, unknown> = {};
  try {
    profile = JSON.parse(await fs.promises.readFile(filePath, 'utf8')) as Record<string, unknown>;
  } catch {
    profile = {};
  }
  delete profile.passphrase;
  profile.registered = true;
  await writeJsonAtomic(filePath, profile);
}

function e2eeAlreadyRegistered(filePath: string): boolean {
  try {
    const m = JSON.parse(fs.readFileSync(filePath, 'utf8')) as Record<string, unknown>;
    return m.registered === true;
  } catch {
    return false;
  }
}

export async function e2eeGenerateLocal(rt: Runtime, args: Record<string, unknown>) {
  requireGate(rt, 'setup_auth');
  const argsPassphrase = optionalString(args, 'passphrase');
  if (argsPassphrase) {
    return textError(
      'passphrase in tool args is not allowed via MCP — omit passphrase for auto-generate, or use CLI: npx @tmail/mcp e2ee-passphrase set',
    );
  }

  let register = true;
  if (typeof args.register === 'boolean') register = args.register;

  if (e2eeAlreadyRegistered(rt.paths.e2eeFile)) {
    return resolveErrorResult(
      newResolveError(
        ERR_E2EE_ALREADY_REGISTERED,
        'e2ee.json already registered for this wallet',
        'Remove e2ee.json manually or use a different wallet_slug',
      ),
    );
  }

  await migrateLegacyPassphraseInJson(rt.paths);

  let resolved: Awaited<ReturnType<typeof resolvePassphrase>>;
  try {
    resolved = await resolvePassphrase(rt.paths, {
      envFallback: rt.cfg.e2eePassphrase,
      autoGenerate: true,
    });
  } catch (err) {
    return textError(err instanceof Error ? err.message : String(err));
  }

  let out: Record<string, unknown>;
  try {
    out = await generateE2EEKeyPairLocal(resolved.passphrase);
  } catch (err) {
    return textError(err instanceof Error ? err.message : String(err));
  }
  out.registered = false;

  try {
    await writeE2EEProfile(rt.paths.e2eeFile, out);
  } catch (err) {
    return textError(`generate ok but e2ee.json write failed: ${err instanceof Error ? err.message : String(err)}`);
  }

  if (register) {
    const pub = typeof out.pub_key_base64 === 'string' ? out.pub_key_base64 : '';
    try {
      await rt.client.put('/api/tbox/keys', { pub_key_e2e: pub });
    } catch (err) {
      return textError(`local keygen ok but register failed: ${err instanceof Error ? err.message : String(err)}`);
    }
    out.registered = true;
    try {
      await mergeE2EERegistered(rt.paths.e2eeFile);
    } catch (err) {
      return textError(`register ok but e2ee.json update failed: ${err instanceof Error ? err.message : String(err)}`);
    }
    if (typeof out.warning === 'string') {
      out.warning += ' Public key registered via PUT /api/tbox/keys.';
    }
  }

  const sanitized = sanitizeForTool('tmail_e2ee_generate_local', out) as Record<string, unknown>;
  sanitized.passphrase_auto_generated = resolved.autoGenerated;
  sanitized.passphrase_user_set = false;
  return textResult(withProfileContext(rt.paths.walletSlug, rt.paths.dir, sanitized, rt.cfg.redactPaths));
}

export async function e2eeRegister(rt: Runtime, args: Record<string, unknown>) {
  requireGate(rt, 'setup_auth');
  let pub: string;
  try {
    pub = requireString(args, 'pub_key_base64');
  } catch {
    return textError('pub_key_base64 is required');
  }
  const out = await rt.client.put<Record<string, unknown>>('/api/tbox/keys', { pub_key_e2e: pub });
  try {
    await mergeE2EERegistered(rt.paths.e2eeFile);
  } catch (err) {
    return textError(`register ok but e2ee.json update failed: ${err instanceof Error ? err.message : String(err)}`);
  }
  const sanitized = sanitizeForTool('tmail_e2ee_register', out) as Record<string, unknown>;
  return textResult(withProfileContext(rt.paths.walletSlug, rt.paths.dir, sanitized, rt.cfg.redactPaths));
}

export async function e2eeGet(rt: Runtime) {
  requireGate(rt, 'mail_ops');
  const out = await rt.client.get<Record<string, unknown>>('/api/tbox/keys');
  return textResult(sanitizeForTool('tmail_e2ee_get', out));
}

export async function e2eeLookup(rt: Runtime, args: Record<string, unknown>) {
  requireGate(rt, 'mail_ops');
  let addresses: string[];
  try {
    addresses = requireStringArray(args, 'addresses');
  } catch {
    return textError('addresses is required (array of mailbox addresses, max 20)');
  }
  if (addresses.length > 20) return textError('too many addresses (max 20)');
  const out = await rt.client.post<Record<string, unknown>>('/api/tbox/keys/lookup', { addresses });
  return textResult(sanitizeForTool('tmail_e2ee_lookup', out));
}

export async function e2eePassphraseStatusTool(rt: Runtime) {
  requireGate(rt, 'setup_auth');
  const status = await passphraseStatus(rt.paths, rt.cfg.e2eePassphrase);
  return textResult(
    withProfileContext(
      rt.paths.walletSlug,
      rt.paths.dir,
      { passphrase: status },
      rt.cfg.redactPaths,
    ),
  );
}

export async function e2eePassphraseRevealTool(_rt: Runtime) {
  requireHumanOnly();
}

export async function e2eeChangePassphraseTool(_rt: Runtime, _args: Record<string, unknown>) {
  requireHumanOnly();
}

export async function changePassphraseForProfile(
  rt: Runtime,
  newPassphrase: string,
): Promise<{ ok: true } | { ok: false; error: string }> {
  if (newPassphrase.length < 16) {
    return { ok: false, error: 'new passphrase must be at least 16 characters' };
  }

  let profile: Record<string, unknown>;
  try {
    profile = JSON.parse(await fs.promises.readFile(rt.paths.e2eeFile, 'utf8')) as Record<string, unknown>;
  } catch {
    return { ok: false, error: 'e2ee.json not found — run e2ee_generate_local first' };
  }

  const enc = typeof profile.enc_priv_key_base64 === 'string' ? profile.enc_priv_key_base64 : '';
  const salt = typeof profile.pbkdf2_salt === 'string' ? profile.pbkdf2_salt : '';
  const iterations =
    typeof profile.pbkdf2_iterations === 'number' ? profile.pbkdf2_iterations : 600_000;
  const pub = typeof profile.pub_key_base64 === 'string' ? profile.pub_key_base64 : '';

  if (!enc || !salt || !pub) {
    return { ok: false, error: 'e2ee.json missing enc_priv_key_base64, pbkdf2_salt, or pub_key_base64' };
  }

  await migrateLegacyPassphraseInJson(rt.paths);

  let oldPassphrase = await readPassphraseFile(rt.paths.e2eePassphraseFile);
  if (!oldPassphrase && rt.cfg.e2eePassphrase) {
    oldPassphrase = rt.cfg.e2eePassphrase;
  }
  if (!oldPassphrase && typeof profile.passphrase === 'string') {
    oldPassphrase = profile.passphrase;
  }
  if (!oldPassphrase) {
    return { ok: false, error: 'no current passphrase — use e2ee-passphrase reveal or check e2ee.passphrase file' };
  }

  let privateKey: Uint8Array;
  try {
    privateKey = unlockPrivateKey(enc, salt, iterations, oldPassphrase);
  } catch {
    return { ok: false, error: 'failed to decrypt private key — wrong passphrase?' };
  }

  if (!verifyPrivateKeyMatchesPub(privateKey, pub)) {
    privateKey.fill(0);
    return { ok: false, error: 'decrypted key does not match pub_key_base64' };
  }

  let reenc: Awaited<ReturnType<typeof reencryptPrivateKey>>;
  try {
    reenc = await reencryptPrivateKey(privateKey, newPassphrase);
  } catch (err) {
    privateKey.fill(0);
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  } finally {
    privateKey.fill(0);
  }

  profile.enc_priv_key_base64 = reenc.enc_priv_key_base64;
  profile.pbkdf2_salt = reenc.pbkdf2_salt;
  profile.pbkdf2_iterations = reenc.pbkdf2_iterations;
  delete profile.passphrase;

  try {
    await writeJsonAtomic(rt.paths.e2eeFile, profile);
    await writePassphrase(rt.paths, newPassphrase, true);
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }

  return { ok: true };
}

export async function revealPassphraseForProfile(rt: Runtime): Promise<string | null> {
  await migrateLegacyPassphraseInJson(rt.paths);
  const fromFile = await readPassphraseFile(rt.paths.e2eePassphraseFile);
  if (fromFile) return fromFile;
  if (rt.cfg.e2eePassphrase) return rt.cfg.e2eePassphrase;
  try {
    const profile = JSON.parse(await fs.promises.readFile(rt.paths.e2eeFile, 'utf8')) as Record<string, unknown>;
    if (typeof profile.passphrase === 'string' && profile.passphrase.trim()) {
      return profile.passphrase.trim();
    }
  } catch {
    // no e2ee.json
  }
  return null;
}
